<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoCitas', 'doctrine');

/**
 * BaseTipoCitas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo
 * @property string $nombre
 * @property Doctrine_Collection $Citas
 * 
 * @method integer             getIdTipo()  Returns the current record's "id_tipo" value
 * @method string              getNombre()  Returns the current record's "nombre" value
 * @method Doctrine_Collection getCitas()   Returns the current record's "Citas" collection
 * @method TipoCitas           setIdTipo()  Sets the current record's "id_tipo" value
 * @method TipoCitas           setNombre()  Sets the current record's "nombre" value
 * @method TipoCitas           setCitas()   Sets the current record's "Citas" collection
 * 
 * @package    sistemacitas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoCitas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_citas');
        $this->hasColumn('id_tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Citas', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo'));
    }
}