<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/14 23:48:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dbcitas',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
