<?php

/**
 * Citas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sistemacitas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Citas extends BaseCitas
{
    public static function ingresarCita($entrada){
        if(isset($entrada['idCliente']))
            $idCliente = $entrada['idCliente'];
        else
            return "No se identifico ningun cliente";
        if(isset($entrada['fecha']))
            $fecha = $entrada['fecha'];
        else
            return "No se identifico ningun cliente";
        
        $cita = new Citas();
        $cita->setIdClientes($idCliente);
        $cita->setFecha($fecha);
        $cita->setIdTipo(1);
        $cita->save();
        return "La solicitud se realizo con exito";
        
    }
}
