<?php

/**
 * ClientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clientes');
    }
}