<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/12 20:11:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dbcitas',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
